name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: configure
    #   run: ./configure

    - name: Build
      run: make

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
    - name: Upload quickinstall release
      uses: actions/upload-artifact@v4
      with:
        name: quickinstall
        path: dist/RoR2UA.zip

    - name: Upload Thunderstore release
      uses: actions/upload-artifact@v4
      with:
        name: thunderstore-release
        path: dist/RoR2UA-Thunderstore.zip
