name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # - name: configure
    #   run: ./configure

    - name: Build
      run: make

    # - name: Run check
    #   run: make check

    # - name: Run distcheck
    #   run: make distcheck
    - name: Upload builds
      uses: actions/upload-artifact@v4
      with:
        name: builds
        path: dist/
